default: &default
  adapter: postgresql
  host: localhost
  username:
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: wanderbuilt_dev

test:
  <<: *default
  database: wanderbuilt_test

production:
  <<: *default
  database: wanderbuilt
